[package]
name = "rust_ffi_byte_buffer"
version = "0.1.0"
authors = ["Fernando Lopes <fernando.lopes@freenet.de>"]
license = "MIT"
description = "Byte buffer utilities to send bytes across FFI."
repository = "https://github.com/da-ferdl/rust_ffi_byte_buffer"
readme = "README.md"
edition = "2024"
