[package]
name = "ffi-byte-buffer"
version = "0.1.0"
authors = ["Fernando Lopes <fernando.lopes@freenet.de>"]
license = "MIT"
description = "Rust byte buffer utilities to send bytes across FFI."
repository = "https://github.com/da-ferdl/ffi-byte-buffer"
readme = "README.md"
edition = "2024"
